artifact_location: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/0
creation_time: 1724922820690
experiment_id: '0'
last_update_time: 1724922820690
lifecycle_stage: active
name: Default
