artifact_uri: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/450585804977983316/e9b78220f75a4a8c88769ea46d815bcc/artifacts
end_time: 1724923044581
entry_point_name: ''
experiment_id: '450585804977983316'
lifecycle_stage: active
run_id: e9b78220f75a4a8c88769ea46d815bcc
run_name: Random Forest
run_uuid: e9b78220f75a4a8c88769ea46d815bcc
source_name: ''
source_type: 4
source_version: ''
start_time: 1724923042034
status: 3
tags: []
user_id: your user name
