artifact_uri: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/450585804977983316/4fd3e2a7dc2d4bf19742bc5b03e67f9e/artifacts
end_time: 1724923042029
entry_point_name: ''
experiment_id: '450585804977983316'
lifecycle_stage: active
run_id: 4fd3e2a7dc2d4bf19742bc5b03e67f9e
run_name: Logistic Regression
run_uuid: 4fd3e2a7dc2d4bf19742bc5b03e67f9e
source_name: ''
source_type: 4
source_version: ''
start_time: 1724923039511
status: 3
tags: []
user_id: your user name
