channels:
- conda-forge
dependencies:
- python=3.8.8
- pip<=21.0.1
- pip:
  - mlflow==2.15.1
  - lz4==4.3.2
  - mypy-extensions==0.4.3
  - numpy==1.22.4
  - pandas==1.5.3
  - psutil==5.8.0
  - scikit-learn==0.24.1
  - scipy==1.6.2
  - xgboost==1.4.2
name: mlflow-env
