artifact_uri: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/450585804977983316/9ff31acc6d0e43448a482aec9545b293/artifacts
end_time: 1724922913766
entry_point_name: ''
experiment_id: '450585804977983316'
lifecycle_stage: active
run_id: 9ff31acc6d0e43448a482aec9545b293
run_name: XGBClassifier
run_uuid: 9ff31acc6d0e43448a482aec9545b293
source_name: ''
source_type: 4
source_version: ''
start_time: 1724922911290
status: 3
tags: []
user_id: your user name
