artifact_uri: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/450585804977983316/21d2a36b93f643ef8382f730f1e6a33a/artifacts
end_time: 1724922916312
entry_point_name: ''
experiment_id: '450585804977983316'
lifecycle_stage: active
run_id: 21d2a36b93f643ef8382f730f1e6a33a
run_name: XGBClassifier With SMOTE
run_uuid: 21d2a36b93f643ef8382f730f1e6a33a
source_name: ''
source_type: 4
source_version: ''
start_time: 1724922913769
status: 3
tags: []
user_id: your user name
