channels:
- conda-forge
dependencies:
- python=3.8.8
- pip<=21.0.1
- pip:
  - mlflow==2.15.1
  - cloudpickle==1.6.0
  - lz4==4.3.2
  - numpy==1.22.4
  - psutil==5.8.0
  - scikit-learn==0.24.1
  - scipy==1.6.2
name: mlflow-env
