artifact_location: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/450585804977983316
creation_time: 1724922906245
experiment_id: '450585804977983316'
last_update_time: 1724922906245
lifecycle_stage: active
name: test1
