artifact_location: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/760799707792981523
creation_time: 1724922820707
experiment_id: '760799707792981523'
last_update_time: 1724922820707
lifecycle_stage: active
name: Anomaly Detection
