artifact_uri: file:///C:/Users/ankit_aj/Desktop/MLOPS-case_studies/Dagshub_demo_mlflow/dagshub_mlflow/your
  dagshub unique uri/760799707792981523/bfd98f85bcc3477ca96c89972b5d64bb/artifacts
end_time: 1724922824549
entry_point_name: ''
experiment_id: '760799707792981523'
lifecycle_stage: active
run_id: bfd98f85bcc3477ca96c89972b5d64bb
run_name: Logistic Regression
run_uuid: bfd98f85bcc3477ca96c89972b5d64bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1724922820818
status: 3
tags: []
user_id: your user name
